
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author cesar31
 */
public class VentanaReportes extends javax.swing.JFrame {

    Ventana ventana;
    DefaultTableModel modelo1 = new DefaultTableModel();
    TableRowSorter<TableModel> name1 = new TableRowSorter<TableModel>(modelo1);
    
    public VentanaReportes(Ventana ventana) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.ventana = ventana;
        
    }

    public void agregarFilaTabla(String nombre){
        String [] elementos = new String[4];
        elementos[0]=nombre;
        modelo1.addRow(elementos);
        tablapor.setModel(modelo1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresar = new javax.swing.JButton();
        subVentanaReport = new javax.swing.JTabbedPane();
        panelHOY = new javax.swing.JPanel();
        scrollHOy = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        panelMora = new javax.swing.JPanel();
        scrollMOra = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        panelEstadistica = new javax.swing.JPanel();
        dias = new javax.swing.JLabel();
        cajaDias = new javax.swing.JTextField();
        BtnBuscardias = new javax.swing.JButton();
        scrollEstadistica = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panelEstCar = new javax.swing.JPanel();
        cajaFiltros = new javax.swing.JTextField();
        filtroEstado = new javax.swing.JComboBox<>();
        BtnBuscar = new javax.swing.JButton();
        filtroDatos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablapor = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reportes");
        setAlwaysOnTop(true);

        regresar.setText("Back");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        scrollHOy.setViewportView(jTextArea2);

        javax.swing.GroupLayout panelHOYLayout = new javax.swing.GroupLayout(panelHOY);
        panelHOY.setLayout(panelHOYLayout);
        panelHOYLayout.setHorizontalGroup(
            panelHOYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHOYLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollHOy, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelHOYLayout.setVerticalGroup(
            panelHOYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHOYLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollHOy, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addContainerGap())
        );

        subVentanaReport.addTab("Hoy", panelHOY);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        scrollMOra.setViewportView(jTextArea3);

        javax.swing.GroupLayout panelMoraLayout = new javax.swing.GroupLayout(panelMora);
        panelMora.setLayout(panelMoraLayout);
        panelMoraLayout.setHorizontalGroup(
            panelMoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMoraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollMOra, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMoraLayout.setVerticalGroup(
            panelMoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMoraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollMOra, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addContainerGap())
        );

        subVentanaReport.addTab("Dev. Mora", panelMora);

        dias.setText("Dias: ");

        BtnBuscardias.setText("Buscar");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        scrollEstadistica.setViewportView(jTextArea1);

        javax.swing.GroupLayout panelEstadisticaLayout = new javax.swing.GroupLayout(panelEstadistica);
        panelEstadistica.setLayout(panelEstadisticaLayout);
        panelEstadisticaLayout.setHorizontalGroup(
            panelEstadisticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadisticaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEstadisticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollEstadistica)
                    .addGroup(panelEstadisticaLayout.createSequentialGroup()
                        .addComponent(dias, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cajaDias, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnBuscardias, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 345, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelEstadisticaLayout.setVerticalGroup(
            panelEstadisticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadisticaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEstadisticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dias, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscardias, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollEstadistica, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                .addContainerGap())
        );

        subVentanaReport.addTab("Estadisticas", panelEstadistica);

        filtroEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Actual", "Todos" }));
        filtroEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroEstadoActionPerformed(evt);
            }
        });

        BtnBuscar.setText("Buscar");
        BtnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnBuscarMouseClicked(evt);
            }
        });

        filtroDatos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carnet", "Carrera" }));

        tablapor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablapor);

        javax.swing.GroupLayout panelEstCarLayout = new javax.swing.GroupLayout(panelEstCar);
        panelEstCar.setLayout(panelEstCarLayout);
        panelEstCarLayout.setHorizontalGroup(
            panelEstCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstCarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEstCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                    .addGroup(panelEstCarLayout.createSequentialGroup()
                        .addComponent(filtroDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cajaFiltros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filtroEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelEstCarLayout.setVerticalGroup(
            panelEstCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstCarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEstCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtroEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtroDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                .addContainerGap())
        );

        subVentanaReport.addTab("Por Estudiante/Carrera", panelEstCar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(regresar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(subVentanaReport))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subVentanaReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regresar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ventana.setVisible(true);
    }//GEN-LAST:event_regresarActionPerformed

    private void filtroEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtroEstadoActionPerformed

    private void BtnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBuscarMouseClicked
        if(){
            
        }
        
    }//GEN-LAST:event_BtnBuscarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnBuscardias;
    private javax.swing.JTextField cajaDias;
    private javax.swing.JTextField cajaFiltros;
    private javax.swing.JLabel dias;
    private javax.swing.JComboBox<String> filtroDatos;
    private javax.swing.JComboBox<String> filtroEstado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JPanel panelEstCar;
    private javax.swing.JPanel panelEstadistica;
    private javax.swing.JPanel panelHOY;
    private javax.swing.JPanel panelMora;
    private javax.swing.JButton regresar;
    private javax.swing.JScrollPane scrollEstadistica;
    private javax.swing.JScrollPane scrollHOy;
    private javax.swing.JScrollPane scrollMOra;
    private javax.swing.JTabbedPane subVentanaReport;
    private javax.swing.JTable tablapor;
    // End of variables declaration//GEN-END:variables

public void carnetTodos(int carnet){
    ventana.tx.datos.register=ventana.arregloPrestamos();
    
    for (int i = 0; i < ventana.tx.datos.register.size(); i++) {
        if(ventana.tx.datos.register.get(i).carnetE==carnet){
            if(ventana.tx.datos.register.get(i).estado){
                agregarFilaTabla(ventana.tx.datos.register.get(i).codigoL);
                if(ventana.tx.datos.register.get(i).estado2){
                    agregarFilaTabla(ventana.tx.datos.register.get(i).codigoL);
                }
                if(ventana.tx.datos.register.get(i).estado3){
                    agregarFilaTabla(ventana.tx.datos.register.get(i).codigoL);
                }
            }
        }
        
    }
    
}






}
