
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author cesar31
 */
public class VentanaPrestamos extends javax.swing.JFrame {

    Ventana ventana;
    String codigoL;
    int carnetE;
    int dias;
    
    public VentanaPrestamos(Ventana ventana) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.ventana = ventana;
        cajaCarnet.setEditable(false);
        BtnVerificar.setEnabled(false);
        BtnConfirmar.setEnabled(false);
        BtnAceptar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresarInicio = new javax.swing.JButton();
        subPrestamos = new javax.swing.JTabbedPane();
        panelPrestar = new javax.swing.JPanel();
        codigo = new javax.swing.JLabel();
        cajaCodigo = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        textoBuscar = new javax.swing.JLabel();
        carnet = new javax.swing.JLabel();
        cajaCarnet = new javax.swing.JTextField();
        BtnVerificar = new javax.swing.JButton();
        txtInformacion = new javax.swing.JLabel();
        BtnConfirmar = new javax.swing.JButton();
        panelDevolver = new javax.swing.JPanel();
        tCodigo = new javax.swing.JLabel();
        cajaTCodigo = new javax.swing.JTextField();
        tCarnet = new javax.swing.JLabel();
        cajaTCarnet = new javax.swing.JTextField();
        BtnCalcular = new javax.swing.JButton();
        Pagar = new javax.swing.JLabel();
        BtnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prestamos");

        regresarInicio.setText("Back");
        regresarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarInicioActionPerformed(evt);
            }
        });

        codigo.setText("Codigo: ");

        cajaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaCodigoActionPerformed(evt);
            }
        });

        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        textoBuscar.setText("Buscando Libro...");

        carnet.setText("Carnet: ");

        BtnVerificar.setText("Verificar");
        BtnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerificarActionPerformed(evt);
            }
        });

        BtnConfirmar.setText("Confirmar");
        BtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrestarLayout = new javax.swing.GroupLayout(panelPrestar);
        panelPrestar.setLayout(panelPrestarLayout);
        panelPrestarLayout.setHorizontalGroup(
            panelPrestarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrestarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrestarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelPrestarLayout.createSequentialGroup()
                        .addGroup(panelPrestarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtInformacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelPrestarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelPrestarLayout.createSequentialGroup()
                                    .addComponent(codigo)
                                    .addGap(18, 18, 18)
                                    .addComponent(cajaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(BtnBuscar))
                                .addGroup(panelPrestarLayout.createSequentialGroup()
                                    .addComponent(carnet)
                                    .addGap(18, 18, 18)
                                    .addComponent(cajaCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(BtnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelPrestarLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(BtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPrestarLayout.setVerticalGroup(
            panelPrestarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrestarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrestarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelPrestarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cajaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrestarLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(BtnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPrestarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carnet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnVerificar))
                .addGap(18, 18, 18)
                .addComponent(txtInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnConfirmar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        subPrestamos.addTab("Prestar", panelPrestar);

        tCodigo.setText("Codigo:");

        cajaTCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTCodigoActionPerformed(evt);
            }
        });

        tCarnet.setText("Carnet: ");

        BtnCalcular.setText("Calcular");
        BtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalcularActionPerformed(evt);
            }
        });

        BtnAceptar.setText("Aceptar");
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDevolverLayout = new javax.swing.GroupLayout(panelDevolver);
        panelDevolver.setLayout(panelDevolverLayout);
        panelDevolverLayout.setHorizontalGroup(
            panelDevolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDevolverLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(BtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(panelDevolverLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDevolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDevolverLayout.createSequentialGroup()
                        .addGroup(panelDevolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tCarnet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDevolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cajaTCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(cajaTCarnet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDevolverLayout.setVerticalGroup(
            panelDevolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDevolverLayout.createSequentialGroup()
                .addGroup(panelDevolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDevolverLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelDevolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajaTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelDevolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tCarnet)
                            .addComponent(cajaTCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDevolverLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(BtnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnAceptar)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        subPrestamos.addTab("Devolver", panelDevolver);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subPrestamos)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(regresarInicio)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subPrestamos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regresarInicio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarInicioActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ventana.setVisible(true);
    }//GEN-LAST:event_regresarInicioActionPerformed

    private void cajaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaCodigoActionPerformed

    private void BtnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerificarActionPerformed
        // TODO add your handling code here:
        
        if(!cajaCarnet.getText().equals("")){
            carnetE = Integer.parseInt(cajaCarnet.getText());
            if(ventana.registros.buscarEstudiante(carnetE)){
                ventana.cargarEstudiantes(carnetE);
                if(ventana.tmpE.getLimite()<3){
                    BtnConfirmar.setEnabled(true);
                    txtInformacion.setText("Presione confirmar para completar");
                }else{
                    txtInformacion.setText("Tiene 3 libros en posesion");
                }
            }else{
                txtInformacion.setText("Carnet no registrado o invalido");
            }
            
        }
    }//GEN-LAST:event_BtnVerificarActionPerformed

    private void cajaTCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTCodigoActionPerformed

    private void BtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcularActionPerformed
        // TODO add your handling code here:
        if(!cajaTCodigo.getText().equals("") && !cajaTCarnet.getText().equals("")){
            if(ventana.registros.buscarRegistro(cajaTCodigo.getText(), Integer.parseInt(cajaTCarnet.getText()))){
                ventana.cargarPrestamos(cajaTCodigo.getText(), Integer.parseInt(cajaCarnet.getText()));
                if(ventana.tmpP.getCantidad()>0){
                    codigoL = cajaTCodigo.getText();
                    carnetE = Integer.parseInt(cajaTCarnet.getText());
                    ventana.cargarPrestamos(codigoL, carnetE);
                     BtnAceptar.setEnabled(true);
                    try {
                         hacerCalculos();
                    }catch (ParseException ex) {
                        Logger.getLogger(VentanaPrestamos.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else{
                   Pagar.setText("Deudas ya cubieras"); 
                }
            }else{
                Pagar.setText("Carnet y/o codigo equivocados");
            }
        }else{
            Pagar.setText("Ingrese un carnet y un codigo");
        }
        
    }//GEN-LAST:event_BtnCalcularActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        // TODO add your handling code here:
        if(!cajaCodigo.getText().equals("")){
                
            if(ventana.registros.buscarLibro(cajaCodigo.getText())){
                if(ventana.registros.LibrosEnexistencia(cajaCodigo.getText())>0){
                    prestarLibro();
                }else{
                   cajaCodigo.setText("");
                   textoBuscar.setText("Libro no disponible"); 
                }
            }else{
                cajaCodigo.setText("");
                textoBuscar.setText("El libro no existe en la biblioteca");
            }
        }else{
            textoBuscar.setText("Ingrese el codigo del libro");
        }
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void BtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfirmarActionPerformed
        // TODO add your handling code here:
        operacionesPrestamo();
    }//GEN-LAST:event_BtnConfirmarActionPerformed

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        try {
            // TODO add your handling code here:
            operacionesDevolucion();
        } catch (ParseException ex) {
            Logger.getLogger(VentanaPrestamos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnCalcular;
    private javax.swing.JButton BtnConfirmar;
    private javax.swing.JButton BtnVerificar;
    private javax.swing.JLabel Pagar;
    private javax.swing.JTextField cajaCarnet;
    private javax.swing.JTextField cajaCodigo;
    private javax.swing.JTextField cajaTCarnet;
    private javax.swing.JTextField cajaTCodigo;
    private javax.swing.JLabel carnet;
    private javax.swing.JLabel codigo;
    private javax.swing.JPanel panelDevolver;
    private javax.swing.JPanel panelPrestar;
    private javax.swing.JButton regresarInicio;
    private javax.swing.JTabbedPane subPrestamos;
    private javax.swing.JLabel tCarnet;
    private javax.swing.JLabel tCodigo;
    private javax.swing.JLabel textoBuscar;
    private javax.swing.JLabel txtInformacion;
    // End of variables declaration//GEN-END:variables

    public void prestarLibro(){

        textoBuscar.setText("Copias disponibles: "+ventana.registros.LibrosEnexistencia(cajaCodigo.getText()));
        codigoL = cajaCodigo.getText();
        cajaCarnet.setEditable(true);
        BtnVerificar.setEnabled(true);
    }
    
    public void operacionesPrestamo(){
        ventana.cargarLibros(codigoL);
        ventana.tmpL.cantidad--;
        ventana.tx.guardarLibros(codigoL, ventana.tmpL);
        
        ventana.cargarEstudiantes(carnetE);
        ventana.tmpE.limite++;
        ventana.tx.guardarEstudiantes(carnetE, ventana.tmpE);
        
        if(ventana.registros.buscarRegistro(codigoL, carnetE)){
            ventana.cargarPrestamos(codigoL, carnetE);
            ventana.tmpP.cantidad++;
            if(ventana.tmpP.cantidad==2){
                ventana.tmpP.estado2 = true;
                ventana.tmpP.setFechaPrestamo2(ventana.registros.fechaHoy());
            }else if(ventana.tmpP.cantidad==3){
                ventana.tmpP.estado3 = true;
                ventana.tmpP.setFechaPrestamo3(ventana.registros.fechaHoy());
            }
            ventana.tx.guardarPrestamos(codigoL, carnetE, ventana.tmpP);
        }else{
            Prestamo tmp = new Prestamo(carnetE, codigoL, ventana.registros.fechaHoy());
            ventana.tx.guardarPrestamos(codigoL, carnetE, tmp);
        }
        cajaCodigo.setText("");
        cajaCarnet.setText("");
        cajaCarnet.setEditable(false);
        BtnVerificar.setEnabled(false);
        BtnConfirmar.setEnabled(false);
        
        txtInformacion.setText("Prestamo completado");
        codigoL = null;
        carnetE = 0;
    }
    
    public void hacerCalculos() throws ParseException{
                        
        if(ventana.tmpP.getCantidad()==3){
            dias = ventana.registros.diferenciaDias(ventana.tmpP.fechaPrestamo3);
            ventana.tmpP.montoAPagar = ventana.registros.calcularMonto(ventana.registros.diferenciaDias((ventana.tmpP.fechaPrestamo3)));
            Pagar.setText("El monto total a pagar es: "+ventana.tmpP.montoAPagar);
        }
        if(ventana.tmpP.getCantidad()==2){
            dias = ventana.registros.diferenciaDias(ventana.tmpP.fechaPrestamo2);
            ventana.tmpP.montoAPagar = ventana.registros.calcularMonto(ventana.registros.diferenciaDias((ventana.tmpP.fechaPrestamo2)));
            Pagar.setText("El monto total a pagar es: "+ventana.tmpP.montoAPagar);
        }
        if(ventana.tmpP.getCantidad()==1){
            dias = ventana.registros.diferenciaDias(ventana.tmpP.fechaPrestamo);
            ventana.tmpP.montoAPagar = ventana.registros.calcularMonto(ventana.registros.diferenciaDias((ventana.tmpP.fechaPrestamo)));
            Pagar.setText("El monto total a pagar es: "+ventana.tmpP.montoAPagar);
        }
    }
    
    public void operacionesDevolucion() throws ParseException{
        ventana.cargarLibros(codigoL);
        ventana.tmpL.cantidad++;
        ventana.tx.guardarLibros(codigoL, ventana.tmpL);
        
        ventana.cargarEstudiantes(carnetE);
        ventana.tmpE.limite--;
        ventana.tx.guardarEstudiantes(carnetE, ventana.tmpE);
        
        ventana.cargarPrestamos(codigoL, carnetE);
        ventana.tmpP.cantidad--;
        if(ventana.tmpP.getCantidad() == 2){
            ventana.tmpP.montoAPagar = ventana.registros.calcularMonto(ventana.registros.diferenciaDias(ventana.tmpP.fechaPrestamo3));
            ventana.tmpP.fechaPrestamo3 = null;
            ventana.tmpP.estado3 = false;
        }
        if(ventana.tmpP.getCantidad() == 1){
            ventana.tmpP.montoAPagar = ventana.registros.calcularMonto(ventana.registros.diferenciaDias(ventana.tmpP.fechaPrestamo2));
            ventana.tmpP.fechaPrestamo2 = null;
            ventana.tmpP.estado2 = false;
        }
        if(ventana.tmpP.getCantidad() ==0 ){
            ventana.tmpP.montoAPagar = ventana.registros.calcularMonto(ventana.registros.diferenciaDias(ventana.tmpP.fechaPrestamo));
                    
            ventana.tmpP.fechaPrestamo = null;
            ventana.tmpP.estado = false;
        }
        ventana.tx.guardarPrestamos(codigoL, carnetE, ventana.tmpP);
        cajaTCodigo.setText("");
        cajaTCarnet.setText("");
        codigoL = null;
        carnetE = 0;
        BtnConfirmar.setEnabled(false);
        
    }
}
